### GET /agencies/:id
GET http://localhost:3000/agencies/l12226g3hkctbghzyxw

### PUT /agency OK
PUT  http://localhost:3000/agencies
Content-Type: application/json

{
  "_id" : "l12226g3hkctbghzyxw",
  "name" : "SpaceY",
  "range": "INTERPLANETARY"
}


### GET /agencies/:id
GET http://localhost:3000/agencies/kkl12226g3hkctbghzy

### PUT /agency KO
PUT  http://localhost:3000/agencies
Content-Type: application/json

{
  "_id" : "KK2226g3hkctbghzyxw",
  "name" : "SpaceY",
  "range": "INTERPLANETARY"
}

### POST /agency OK
POST http://localhost:3000/agencies
Content-Type: application/json

{
  "name" : "GreenOrigin"
}