### POST /auth/registration EMPTY
POST http://localhost:3000/auth/registration

### POST /auth/registration BAD
POST http://localhost:3000/auth/registration
Content-Type: application/json

{
  "email" : "billmsft.com"
}

### POST /auth/registration OK
POST http://localhost:3000/auth/registration
Content-Type: application/json

{
  "name" : "Bill",
  "email" : "bill@msft.com",
  "password" : "password"
}

### POST /auth/registration weeellll
POST http://localhost:3000/auth/registration
Content-Type: application/json

{
  "name" : "Bill",
  "email" : "bill@msft.com",
  "password" : "password",
  "passwordConfirmation" : "password"
}


### POST /auth/login BAD
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email" : "bill@msft.com",
  "password" : "badpassword"
}

### POST /auth/login OK
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email" : "bill@msft.com",
  "password" : "password"
}

### GET /auth/
GET http://localhost:3000/auth/

### GET /auth/
GET http://localhost:3000/auth/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsMHZhcTdnNnZoc2N3aGI5enlpIiwiaWF0IjoxNjQ3NTM5OTE2LCJleHAiOjE2NDc1NDAyMTZ9.NfAv0Xs7In8Hi3GZhrglHGbHlE6a9F9W3E6jD9gEa08

### GET /auth/me
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsMHV6ZmVucXkzczB1djF3cTRxIiwiaWF0IjoxNjQ3NTIwOTM2LCJleHAiOjE2NDc1MjEyMzZ9.Cy7UtRdsY-fjVN6fpjsyhNRYzrOxhLPT02h-R4gvO1w