### POST /auth/registration EMPTY
POST http://localhost:3000/auth/registration

### POST /auth/registration BAD
POST http://localhost:3000/auth/registration
Content-Type: application/json

{
  "email" : "billmsft.com"
}

### POST /auth/registration OK
POST http://localhost:3000/auth/registration
Content-Type: application/json

{
  "name" : "Bill",
  "email" : "bill@msft.com",
  "password" : "password"
}

### POST /auth/registration weeellll
POST http://localhost:3000/auth/registration
Content-Type: application/json

{
  "name" : "Bill",
  "email" : "bill@msft.com",
  "password" : "password",
  "passwordConfirmation" : "password"
}


### POST /auth/login BAD
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email" : "bill@msft.com",
  "password" : "badpassword"
}

### POST /auth/login OK
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email" : "bill@msft.com",
  "password" : "password"
}

### GET /auth/
GET http://localhost:3000/auth/

### GET /auth/
GET http://localhost:3000/auth/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsMTJkdDJ0eTJ4YjY2dTMyOWp4IiwiaWF0IjoxNjQ3OTY5MTUzLCJleHAiOjE2NDc5Njk0NTN9.mOeaj6KSsTJBIsauho8JwO2Voh1B1WlhTWSAK0o1-j0

### GET /auth/me
GET http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsMHV6ZmVucXkzczB1djF3cTRxIiwiaWF0IjoxNjQ3NTIwOTM2LCJleHAiOjE2NDc1MjEyMzZ9.Cy7UtRdsY-fjVN6fpjsyhNRYzrOxhLPT02h-R4gvO1w

### POST /auth/registration OK
POST http://localhost:3000/auth/registration
Content-Type: application/json

{
  "name" : "Mark",
  "email" : "mark@meta.com",
  "password" : "password"
}

### POST /auth/login OK
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email" : "mark@meta.com",
  "password" : "password"
}