
### GET /bookings
GET http://localhost:3000/bookings


### POST /bookings
POST http://localhost:3000/bookings
Content-Type: application/json

{
  "client" : "Mark",
  "passengers": 2,
  "tripId": "l157boofiuohk6ojjz"
}

### GET /bookings
GET http://localhost:3000/bookings/l156laft6cd9euoh0jl

### POST /bookings
POST http://localhost:3000/bookings
Content-Type: application/json

{
  "client" : "Amancio",
  "passengers": 5,
  "tripId": "l158kmczr55ai6bn5a",
  "creditCard": "1234567890123456"
}


### POST /bookings
POST http://localhost:3000/bookings
Content-Type: application/json

{
  "client" : "Amancio",
  "passengers": 3,
  "tripId": "l156laft6cd9euoh0jl"
}

### POST /bookings
POST http://localhost:3000/bookings
Content-Type: application/json

{
  "client" : "Warren",
  "passengers": 1,
  "tripId": "l158kmczr55ai6bn5a",
  "creditCard": "1234567890123456"
}